name: BetterWhitelist
author: duper51
main: com.theparkmc.BetterWhitelist.BetterWhitelist
version: 0.2
commands:
  lockdown:
    usage: /<command>
    description: Enables lockdown. Kicks all players off the game except for OPs.
  wl:
    usage: /<command>
    description: Enables whitelist. Leaves players on, but disallows players to rejoin without permissions.
permissions:
  bw.enablewhitelist:
    description: Allows the use of /wl
  bw.allowentry:
    description: Allows players to bypass whitelist